# Etv/AdminBundle/Resources/config/admin.yml
services:
    sonata.admin.etv_user:
        class: Etv\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Etv\AdminBundle\Entity\User
            - ~
#        calls:
#            - [ setTranslationDomain, [AcmeDemoBundle]]