# Etv/AdminBundle/Resources/config/admin.yml
services:
    sonata.admin.admin_user:
        class: Etv\AdminBundle\Admin\AdminUser
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Admin User" }
        arguments:
            - ~
            - Etv\AdminBundle\Entity\AdminUser
            - ~
#        calls:
#            - [ setTranslationDomain, [AcmeDemoBundle]]