parameters:
    webservice_admin_user_provider.class: Etv\AdminBundle\Security\User\AdminWebserviceUserProvider

services:
    webservice_user_provider:
        class: "%webservice_admin_user_provider.class%"