parameters:
#    webservice_admin_user_provider.class: Etv\AdminBundle\Security\AdminWebserviceUserProvider

services:
    etv.admin.etvpw_encoder: 
        class: Etv\AdminBundle\Service\EtvPw
#    webservice_admin_user_provider:
#        class: "%webservice_admin_user_provider.class%"
#        arguments: 
#            - Doctrine
    etv.twig.country_extension:
            class: Etv\AdminBundle\Twig\CountryExtension
            tags:
                - { name: twig.extension }