<?php

namespace Etv\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtvUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtvUserRepository extends EntityRepository
{
}
